// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHV_FFx1-urWXugnb4immvC46yUYZ7H0c',
    appId: '1:400084640544:web:9d02a7e4f2407aafeded45',
    messagingSenderId: '400084640544',
    projectId: 'colorword-e1a91',
    authDomain: 'colorword-e1a91.firebaseapp.com',
    databaseURL: 'https://colorword-e1a91-default-rtdb.firebaseio.com',
    storageBucket: 'colorword-e1a91.appspot.com',
    measurementId: 'G-XERZSY1RXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl1Ad4T2WYNqeNL9RNNMiHS5L9z0oFyOQ',
    appId: '1:400084640544:android:3ce6fdaf772494ceeded45',
    messagingSenderId: '400084640544',
    projectId: 'colorword-e1a91',
    databaseURL: 'https://colorword-e1a91-default-rtdb.firebaseio.com',
    storageBucket: 'colorword-e1a91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPEJnoB19lZwLp0B78aFAileOC8_-IZvc',
    appId: '1:400084640544:ios:48baca4e4eae3394eded45',
    messagingSenderId: '400084640544',
    projectId: 'colorword-e1a91',
    databaseURL: 'https://colorword-e1a91-default-rtdb.firebaseio.com',
    storageBucket: 'colorword-e1a91.appspot.com',
    androidClientId: '400084640544-1gnhf9mq98hpgs30gtt5p0g3rq5d9o6i.apps.googleusercontent.com',
    iosClientId: '400084640544-usf4dk52k67cbqu7ban2ggggncl7m51e.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorwordNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPEJnoB19lZwLp0B78aFAileOC8_-IZvc',
    appId: '1:400084640544:ios:bd9bdec6c13dca9ceded45',
    messagingSenderId: '400084640544',
    projectId: 'colorword-e1a91',
    databaseURL: 'https://colorword-e1a91-default-rtdb.firebaseio.com',
    storageBucket: 'colorword-e1a91.appspot.com',
    androidClientId: '400084640544-1gnhf9mq98hpgs30gtt5p0g3rq5d9o6i.apps.googleusercontent.com',
    iosClientId: '400084640544-cuebd3tmoa2uppqqclknpj6ri6of33kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorwordNew.RunnerTests',
  );
}
